# Generated by Django 4.0.4 on 2022-12-02 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tagging', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tagging',
            old_name='tags',
            new_name='tag',
        ),
        migrations.RenameField(
            model_name='tagging',
            old_name='transactions',
            new_name='transaction',
        ),
    ]
