# Generated by Django 4.0.4 on 2022-12-02 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tagging', '0002_rename_tags_tagging_tag_and_more'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
    ]
